#! /bin/sh -e
# postinst script for ilisp

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see /usr/doc/packaging-manual/
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.


pkg=ilisp
conf_file=/etc/ilisp/ilisp-keybindings.el

if [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
else
    exit 1
fi


set_keybindings()
{
    db_get $pkg/fsf-compliant
    if [ "$RET" = "Yes" ]; then
	echo "(setq ilisp-*use-fsf-compliant-keybindings* t)" > $conf_file
    else
	echo "(setq ilisp-*use-fsf-compliant-keybindings* nil)" > $conf_file
    fi
}


case "$1" in
    configure)
	set_keybindings
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
	;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0


