#! /bin/sh -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>

case "$1" in
    install|upgrade)
	test -e /usr/share/common-lisp/source/ilisp || rm -f /usr/share/common-lisp/source/ilisp
	test -e /usr/share/common-lisp/systems/ilisp.system || rm -f /usr/share/common-lisp/systems/ilisp.system
	;;
    abort-upgrade)
	;;
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0


